/*
Synadia Control Plane / Synadia Cloud

API for Synadia Control Plane / Synadia Cloud

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

// checks if the SDKubeLimit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SDKubeLimit{}

// SDKubeLimit struct for SDKubeLimit
type SDKubeLimit struct {
	FiveNode  int64 `json:"five_node"`
	ThreeNode int64 `json:"three_node"`
}

func (o SDKubeLimit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["five_node"] = o.FiveNode
	toSerialize["three_node"] = o.ThreeNode
	return toSerialize, nil
}
