/*
Synadia Control Plane / Synadia Cloud

API for Synadia Control Plane / Synadia Cloud

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

// checks if the AppPolicyStatement type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppPolicyStatement{}

// AppPolicyStatement struct for AppPolicyStatement
type AppPolicyStatement struct {
	Action      []string        `json:"action"`
	Effect      []AppRoleEffect `json:"effect"`
	Name        string          `json:"name"`
	OperationId *string         `json:"operation_id,omitempty"`
	Resource    []string        `json:"resource"`
	Service     *string         `json:"service,omitempty"`
}

func (o AppPolicyStatement) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	toSerialize["effect"] = o.Effect
	toSerialize["name"] = o.Name
	if o.OperationId != nil {
		toSerialize["operation_id"] = o.OperationId
	}
	toSerialize["resource"] = o.Resource
	if o.Service != nil {
		toSerialize["service"] = o.Service
	}
	return toSerialize, nil
}
