/*
Synadia Control Plane / Synadia Cloud

API for Synadia Control Plane / Synadia Cloud

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

// checks if the ConnectorComponentSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectorComponentSummary{}

// ConnectorComponentSummary struct for ConnectorComponentSummary
type ConnectorComponentSummary struct {
	Icon      *string                  `json:"icon,omitempty"`
	Kind      ConnectorComponentKind   `json:"kind"`
	Label     string                   `json:"label"`
	Name      string                   `json:"name"`
	RuntimeId string                   `json:"runtime_id"`
	Status    ConnectorComponentStatus `json:"status"`
	VersionId string                   `json:"version_id"`
}

func (o ConnectorComponentSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Icon != nil {
		toSerialize["icon"] = o.Icon
	}
	toSerialize["kind"] = o.Kind
	toSerialize["label"] = o.Label
	toSerialize["name"] = o.Name
	toSerialize["runtime_id"] = o.RuntimeId
	toSerialize["status"] = o.Status
	toSerialize["version_id"] = o.VersionId
	return toSerialize, nil
}
