/*
Synadia Control Plane / Synadia Cloud

API for Synadia Control Plane / Synadia Cloud

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

// checks if the UserPermissionLimits type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserPermissionLimits{}

// UserPermissionLimits struct for UserPermissionLimits
type UserPermissionLimits struct {
	Permissions
	UserLimits
	NatsLimits
	AllowedConnectionTypes []string `json:"allowed_connection_types,omitempty"`
	BearerToken            *bool    `json:"bearer_token,omitempty"`
}

func (o UserPermissionLimits) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if len(o.AllowedConnectionTypes) != 0 {
		toSerialize["allowed_connection_types"] = o.AllowedConnectionTypes
	}
	if o.BearerToken != nil {
		toSerialize["bearer_token"] = o.BearerToken
	}
	if o.Pub != nil {
		toSerialize["pub"] = o.Pub
	}
	if o.Resp != nil {
		toSerialize["resp"] = o.Resp
	}
	if o.Sub != nil {
		toSerialize["sub"] = o.Sub
	}
	if len(o.Src) != 0 {
		toSerialize["src"] = o.Src
	}
	if len(o.Times) != 0 {
		toSerialize["times"] = o.Times
	}
	if o.TimesLocation != nil {
		toSerialize["times_location"] = o.TimesLocation
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	if o.Payload != nil {
		toSerialize["payload"] = o.Payload
	}
	if o.Subs != nil {
		toSerialize["subs"] = o.Subs
	}
	return toSerialize, nil
}
