/*
Synadia Control Plane / Synadia Cloud

API for Synadia Control Plane / Synadia Cloud

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

// checks if the ListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListResponse{}

// ListResponse struct for ListResponse
type ListResponse struct {
	Schemas []Schema `json:"schemas"`
}

func (o ListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["schemas"] = o.Schemas
	return toSerialize, nil
}
