/*
Synadia Control Plane / Synadia Cloud

API for Synadia Control Plane / Synadia Cloud

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

// checks if the AdminAppUserCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminAppUserCreateRequest{}

// AdminAppUserCreateRequest struct for AdminAppUserCreateRequest
type AdminAppUserCreateRequest struct {
	GenerateToken *bool  `json:"generate_token,omitempty"`
	Password      string `json:"password"`
	Username      string `json:"username"`
}

func (o AdminAppUserCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.GenerateToken != nil {
		toSerialize["generate_token"] = o.GenerateToken
	}
	toSerialize["password"] = o.Password
	toSerialize["username"] = o.Username
	return toSerialize, nil
}
