/*
Synadia Control Plane / Synadia Cloud

API for Synadia Control Plane / Synadia Cloud

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

import (
	"fmt"

	"encoding/json"
)

// JSPersistMode the model 'JSPersistMode'
type JSPersistMode string

// List of JSPersistMode
const (
	JSPERSISTMODE_DEFAULT JSPersistMode = "default"
	JSPERSISTMODE_ASYNC   JSPersistMode = "async"
)

// All allowed values of JSPersistMode enum
var AllowedJSPersistModeEnumValues = []JSPersistMode{
	"default",
	"async",
}

func (v *JSPersistMode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := JSPersistMode(value)
	for _, existing := range AllowedJSPersistModeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid JSPersistMode", value)
}

// NewJSPersistModeFromValue returns a pointer to a valid JSPersistMode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewJSPersistModeFromValue(v string) (*JSPersistMode, error) {
	ev := JSPersistMode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for JSPersistMode: valid values are %v", v, AllowedJSPersistModeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v JSPersistMode) IsValid() bool {
	for _, existing := range AllowedJSPersistModeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to JSPersistMode value
func (v JSPersistMode) Ptr() *JSPersistMode {
	return &v
}
