/*
Synadia Control Plane

API for Synadia Control Plane Server

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

import (
	"encoding/json"
	"fmt"
)

// checks if the AlertViewResponseSystem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AlertViewResponseSystem{}

// AlertViewResponseSystem struct for AlertViewResponseSystem
type AlertViewResponseSystem struct {
	AgentType            string         `json:"agent_type"`
	Id                   string         `json:"id"`
	IsTenant             bool           `json:"is_tenant"`
	JetstreamDomain      NullableString `json:"jetstream_domain,omitempty"`
	JetstreamEnabled     bool           `json:"jetstream_enabled"`
	JetstreamTiers       []string       `json:"jetstream_tiers,omitempty"`
	Name                 string         `json:"name"`
	ServerUrls           *string        `json:"server_urls,omitempty"`
	State                SystemState    `json:"state"`
	UserJwtExpiresInSecs int64          `json:"user_jwt_expires_in_secs"`
}

type _AlertViewResponseSystem AlertViewResponseSystem

// NewAlertViewResponseSystem instantiates a new AlertViewResponseSystem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlertViewResponseSystem(agentType string, id string, isTenant bool, jetstreamEnabled bool, name string, state SystemState, userJwtExpiresInSecs int64) *AlertViewResponseSystem {
	this := AlertViewResponseSystem{}
	this.AgentType = agentType
	this.Id = id
	this.IsTenant = isTenant
	this.JetstreamEnabled = jetstreamEnabled
	this.Name = name
	this.State = state
	this.UserJwtExpiresInSecs = userJwtExpiresInSecs
	return &this
}

// NewAlertViewResponseSystemWithDefaults instantiates a new AlertViewResponseSystem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlertViewResponseSystemWithDefaults() *AlertViewResponseSystem {
	this := AlertViewResponseSystem{}
	return &this
}

// GetAgentType returns the AgentType field value
func (o *AlertViewResponseSystem) GetAgentType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AgentType
}

// GetAgentTypeOk returns a tuple with the AgentType field value
// and a boolean to check if the value has been set.
func (o *AlertViewResponseSystem) GetAgentTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentType, true
}

// SetAgentType sets field value
func (o *AlertViewResponseSystem) SetAgentType(v string) {
	o.AgentType = v
}

// GetId returns the Id field value
func (o *AlertViewResponseSystem) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AlertViewResponseSystem) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AlertViewResponseSystem) SetId(v string) {
	o.Id = v
}

// GetIsTenant returns the IsTenant field value
func (o *AlertViewResponseSystem) GetIsTenant() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsTenant
}

// GetIsTenantOk returns a tuple with the IsTenant field value
// and a boolean to check if the value has been set.
func (o *AlertViewResponseSystem) GetIsTenantOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsTenant, true
}

// SetIsTenant sets field value
func (o *AlertViewResponseSystem) SetIsTenant(v bool) {
	o.IsTenant = v
}

// GetJetstreamDomain returns the JetstreamDomain field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AlertViewResponseSystem) GetJetstreamDomain() string {
	if o == nil || IsNil(o.JetstreamDomain.Get()) {
		var ret string
		return ret
	}
	return *o.JetstreamDomain.Get()
}

// GetJetstreamDomainOk returns a tuple with the JetstreamDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AlertViewResponseSystem) GetJetstreamDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.JetstreamDomain.Get(), o.JetstreamDomain.IsSet()
}

// HasJetstreamDomain returns a boolean if a field has been set.
func (o *AlertViewResponseSystem) HasJetstreamDomain() bool {
	if o != nil && o.JetstreamDomain.IsSet() {
		return true
	}

	return false
}

// SetJetstreamDomain gets a reference to the given NullableString and assigns it to the JetstreamDomain field.
func (o *AlertViewResponseSystem) SetJetstreamDomain(v string) {
	o.JetstreamDomain.Set(&v)
}

// SetJetstreamDomainNil sets the value for JetstreamDomain to be an explicit nil
func (o *AlertViewResponseSystem) SetJetstreamDomainNil() {
	o.JetstreamDomain.Set(nil)
}

// UnsetJetstreamDomain ensures that no value is present for JetstreamDomain, not even an explicit nil
func (o *AlertViewResponseSystem) UnsetJetstreamDomain() {
	o.JetstreamDomain.Unset()
}

// GetJetstreamEnabled returns the JetstreamEnabled field value
func (o *AlertViewResponseSystem) GetJetstreamEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.JetstreamEnabled
}

// GetJetstreamEnabledOk returns a tuple with the JetstreamEnabled field value
// and a boolean to check if the value has been set.
func (o *AlertViewResponseSystem) GetJetstreamEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JetstreamEnabled, true
}

// SetJetstreamEnabled sets field value
func (o *AlertViewResponseSystem) SetJetstreamEnabled(v bool) {
	o.JetstreamEnabled = v
}

// GetJetstreamTiers returns the JetstreamTiers field value if set, zero value otherwise.
func (o *AlertViewResponseSystem) GetJetstreamTiers() []string {
	if o == nil || IsNil(o.JetstreamTiers) {
		var ret []string
		return ret
	}
	return o.JetstreamTiers
}

// GetJetstreamTiersOk returns a tuple with the JetstreamTiers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertViewResponseSystem) GetJetstreamTiersOk() ([]string, bool) {
	if o == nil || IsNil(o.JetstreamTiers) {
		return nil, false
	}
	return o.JetstreamTiers, true
}

// HasJetstreamTiers returns a boolean if a field has been set.
func (o *AlertViewResponseSystem) HasJetstreamTiers() bool {
	if o != nil && !IsNil(o.JetstreamTiers) {
		return true
	}

	return false
}

// SetJetstreamTiers gets a reference to the given []string and assigns it to the JetstreamTiers field.
func (o *AlertViewResponseSystem) SetJetstreamTiers(v []string) {
	o.JetstreamTiers = v
}

// GetName returns the Name field value
func (o *AlertViewResponseSystem) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AlertViewResponseSystem) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AlertViewResponseSystem) SetName(v string) {
	o.Name = v
}

// GetServerUrls returns the ServerUrls field value if set, zero value otherwise.
func (o *AlertViewResponseSystem) GetServerUrls() string {
	if o == nil || IsNil(o.ServerUrls) {
		var ret string
		return ret
	}
	return *o.ServerUrls
}

// GetServerUrlsOk returns a tuple with the ServerUrls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertViewResponseSystem) GetServerUrlsOk() (*string, bool) {
	if o == nil || IsNil(o.ServerUrls) {
		return nil, false
	}
	return o.ServerUrls, true
}

// HasServerUrls returns a boolean if a field has been set.
func (o *AlertViewResponseSystem) HasServerUrls() bool {
	if o != nil && !IsNil(o.ServerUrls) {
		return true
	}

	return false
}

// SetServerUrls gets a reference to the given string and assigns it to the ServerUrls field.
func (o *AlertViewResponseSystem) SetServerUrls(v string) {
	o.ServerUrls = &v
}

// GetState returns the State field value
func (o *AlertViewResponseSystem) GetState() SystemState {
	if o == nil {
		var ret SystemState
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *AlertViewResponseSystem) GetStateOk() (*SystemState, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *AlertViewResponseSystem) SetState(v SystemState) {
	o.State = v
}

// GetUserJwtExpiresInSecs returns the UserJwtExpiresInSecs field value
func (o *AlertViewResponseSystem) GetUserJwtExpiresInSecs() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.UserJwtExpiresInSecs
}

// GetUserJwtExpiresInSecsOk returns a tuple with the UserJwtExpiresInSecs field value
// and a boolean to check if the value has been set.
func (o *AlertViewResponseSystem) GetUserJwtExpiresInSecsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserJwtExpiresInSecs, true
}

// SetUserJwtExpiresInSecs sets field value
func (o *AlertViewResponseSystem) SetUserJwtExpiresInSecs(v int64) {
	o.UserJwtExpiresInSecs = v
}

func (o AlertViewResponseSystem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AlertViewResponseSystem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["agent_type"] = o.AgentType
	toSerialize["id"] = o.Id
	toSerialize["is_tenant"] = o.IsTenant
	if o.JetstreamDomain.IsSet() {
		toSerialize["jetstream_domain"] = o.JetstreamDomain.Get()
	}
	toSerialize["jetstream_enabled"] = o.JetstreamEnabled
	if !IsNil(o.JetstreamTiers) {
		toSerialize["jetstream_tiers"] = o.JetstreamTiers
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.ServerUrls) {
		toSerialize["server_urls"] = o.ServerUrls
	}
	toSerialize["state"] = o.State
	toSerialize["user_jwt_expires_in_secs"] = o.UserJwtExpiresInSecs
	return toSerialize, nil
}

func (o *AlertViewResponseSystem) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"agent_type",
		"id",
		"is_tenant",
		"jetstream_enabled",
		"name",
		"state",
		"user_jwt_expires_in_secs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAlertViewResponseSystem := _AlertViewResponseSystem{}

	err = json.Unmarshal(bytes, &varAlertViewResponseSystem)

	if err != nil {
		return err
	}

	*o = AlertViewResponseSystem(varAlertViewResponseSystem)

	return err
}

type NullableAlertViewResponseSystem struct {
	value *AlertViewResponseSystem
	isSet bool
}

func (v NullableAlertViewResponseSystem) Get() *AlertViewResponseSystem {
	return v.value
}

func (v *NullableAlertViewResponseSystem) Set(val *AlertViewResponseSystem) {
	v.value = val
	v.isSet = true
}

func (v NullableAlertViewResponseSystem) IsSet() bool {
	return v.isSet
}

func (v *NullableAlertViewResponseSystem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlertViewResponseSystem(val *AlertViewResponseSystem) *NullableAlertViewResponseSystem {
	return &NullableAlertViewResponseSystem{value: val, isSet: true}
}

func (v NullableAlertViewResponseSystem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlertViewResponseSystem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
