/*
Synadia Control Plane

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

import (
	"encoding/json"
)

// checks if the SessionSystemListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SessionSystemListResponse{}

// SessionSystemListResponse struct for SessionSystemListResponse
type SessionSystemListResponse struct {
	Items []SessionSystemListResponseItemsInner `json:"items"`
}

// NewSessionSystemListResponse instantiates a new SessionSystemListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSessionSystemListResponse(items []SessionSystemListResponseItemsInner) *SessionSystemListResponse {
	this := SessionSystemListResponse{}
	this.Items = items
	return &this
}

// NewSessionSystemListResponseWithDefaults instantiates a new SessionSystemListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSessionSystemListResponseWithDefaults() *SessionSystemListResponse {
	this := SessionSystemListResponse{}
	return &this
}

// GetItems returns the Items field value
func (o *SessionSystemListResponse) GetItems() []SessionSystemListResponseItemsInner {
	if o == nil {
		var ret []SessionSystemListResponseItemsInner
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *SessionSystemListResponse) GetItemsOk() ([]SessionSystemListResponseItemsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *SessionSystemListResponse) SetItems(v []SessionSystemListResponseItemsInner) {
	o.Items = v
}

func (o SessionSystemListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SessionSystemListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

type NullableSessionSystemListResponse struct {
	value *SessionSystemListResponse
	isSet bool
}

func (v NullableSessionSystemListResponse) Get() *SessionSystemListResponse {
	return v.value
}

func (v *NullableSessionSystemListResponse) Set(val *SessionSystemListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionSystemListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionSystemListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionSystemListResponse(val *SessionSystemListResponse) *NullableSessionSystemListResponse {
	return &NullableSessionSystemListResponse{value: val, isSet: true}
}

func (v NullableSessionSystemListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionSystemListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
