/*
Synadia Control Plane

API for Synadia Control Plane Server

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

import (
	"encoding/json"
	"time"
)

// checks if the AppUserViewResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppUserViewResponse{}

// AppUserViewResponse struct for AppUserViewResponse
type AppUserViewResponse struct {
	Created    time.Time      `json:"created"`
	Id         string         `json:"id"`
	Identifier NullableString `json:"identifier"`
	Name       string         `json:"name"`
	RoleId     string         `json:"role_id"`
	RoleName   string         `json:"role_name"`
	Type       AppUserType    `json:"type"`
}

// NewAppUserViewResponse instantiates a new AppUserViewResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppUserViewResponse(created time.Time, id string, identifier NullableString, name string, roleId string, roleName string, type_ AppUserType) *AppUserViewResponse {
	this := AppUserViewResponse{}
	this.Created = created
	this.Id = id
	this.Identifier = identifier
	this.Name = name
	this.RoleId = roleId
	this.RoleName = roleName
	this.Type = type_
	return &this
}

// NewAppUserViewResponseWithDefaults instantiates a new AppUserViewResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppUserViewResponseWithDefaults() *AppUserViewResponse {
	this := AppUserViewResponse{}
	return &this
}

// GetCreated returns the Created field value
func (o *AppUserViewResponse) GetCreated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *AppUserViewResponse) GetCreatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *AppUserViewResponse) SetCreated(v time.Time) {
	o.Created = v
}

// GetId returns the Id field value
func (o *AppUserViewResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AppUserViewResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AppUserViewResponse) SetId(v string) {
	o.Id = v
}

// GetIdentifier returns the Identifier field value
// If the value is explicit nil, the zero value for string will be returned
func (o *AppUserViewResponse) GetIdentifier() string {
	if o == nil || o.Identifier.Get() == nil {
		var ret string
		return ret
	}

	return *o.Identifier.Get()
}

// GetIdentifierOk returns a tuple with the Identifier field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AppUserViewResponse) GetIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Identifier.Get(), o.Identifier.IsSet()
}

// SetIdentifier sets field value
func (o *AppUserViewResponse) SetIdentifier(v string) {
	o.Identifier.Set(&v)
}

// GetName returns the Name field value
func (o *AppUserViewResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AppUserViewResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AppUserViewResponse) SetName(v string) {
	o.Name = v
}

// GetRoleId returns the RoleId field value
func (o *AppUserViewResponse) GetRoleId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RoleId
}

// GetRoleIdOk returns a tuple with the RoleId field value
// and a boolean to check if the value has been set.
func (o *AppUserViewResponse) GetRoleIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoleId, true
}

// SetRoleId sets field value
func (o *AppUserViewResponse) SetRoleId(v string) {
	o.RoleId = v
}

// GetRoleName returns the RoleName field value
func (o *AppUserViewResponse) GetRoleName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RoleName
}

// GetRoleNameOk returns a tuple with the RoleName field value
// and a boolean to check if the value has been set.
func (o *AppUserViewResponse) GetRoleNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoleName, true
}

// SetRoleName sets field value
func (o *AppUserViewResponse) SetRoleName(v string) {
	o.RoleName = v
}

// GetType returns the Type field value
func (o *AppUserViewResponse) GetType() AppUserType {
	if o == nil {
		var ret AppUserType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AppUserViewResponse) GetTypeOk() (*AppUserType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AppUserViewResponse) SetType(v AppUserType) {
	o.Type = v
}

func (o AppUserViewResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppUserViewResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["created"] = o.Created
	toSerialize["id"] = o.Id
	toSerialize["identifier"] = o.Identifier.Get()
	toSerialize["name"] = o.Name
	toSerialize["role_id"] = o.RoleId
	toSerialize["role_name"] = o.RoleName
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

type NullableAppUserViewResponse struct {
	value *AppUserViewResponse
	isSet bool
}

func (v NullableAppUserViewResponse) Get() *AppUserViewResponse {
	return v.value
}

func (v *NullableAppUserViewResponse) Set(val *AppUserViewResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAppUserViewResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAppUserViewResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppUserViewResponse(val *AppUserViewResponse) *NullableAppUserViewResponse {
	return &NullableAppUserViewResponse{value: val, isSet: true}
}

func (v NullableAppUserViewResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppUserViewResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
