/*
Synadia Control Plane

API for Synadia Control Plane Server

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

import (
	"time"
)

// checks if the AppUserViewResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppUserViewResponse{}

// AppUserViewResponse struct for AppUserViewResponse
type AppUserViewResponse struct {
	Created         time.Time        `json:"created"`
	Id              string           `json:"id"`
	Identifier      Nullable[string] `json:"identifier"`
	Name            string           `json:"name"`
	PendingCreation bool             `json:"pending_creation"`
	RoleId          string           `json:"role_id"`
	RoleName        string           `json:"role_name"`
	Type            AppUserType      `json:"type"`
}

func (o AppUserViewResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["created"] = o.Created
	toSerialize["id"] = o.Id
	if !o.Identifier.IsNull() {
		toSerialize["identifier"] = o.Identifier.Val
	}
	toSerialize["name"] = o.Name
	toSerialize["pending_creation"] = o.PendingCreation
	toSerialize["role_id"] = o.RoleId
	toSerialize["role_name"] = o.RoleName
	toSerialize["type"] = o.Type
	return toSerialize, nil
}
