/*
Synadia Control Plane

API for Synadia Control Plane Server

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

import (
	"encoding/json"
	"fmt"
)

// checks if the ApexSeries type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApexSeries{}

// ApexSeries struct for ApexSeries
type ApexSeries struct {
	Data []ApexCoordinate `json:"data"`
	Name string           `json:"name"`
}

type _ApexSeries ApexSeries

// NewApexSeries instantiates a new ApexSeries object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApexSeries(data []ApexCoordinate, name string) *ApexSeries {
	this := ApexSeries{}
	this.Data = data
	this.Name = name
	return &this
}

// NewApexSeriesWithDefaults instantiates a new ApexSeries object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApexSeriesWithDefaults() *ApexSeries {
	this := ApexSeries{}
	return &this
}

// GetData returns the Data field value
func (o *ApexSeries) GetData() []ApexCoordinate {
	if o == nil {
		var ret []ApexCoordinate
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ApexSeries) GetDataOk() ([]ApexCoordinate, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ApexSeries) SetData(v []ApexCoordinate) {
	o.Data = v
}

// GetName returns the Name field value
func (o *ApexSeries) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ApexSeries) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ApexSeries) SetName(v string) {
	o.Name = v
}

func (o ApexSeries) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApexSeries) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *ApexSeries) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApexSeries := _ApexSeries{}

	err = json.Unmarshal(bytes, &varApexSeries)

	if err != nil {
		return err
	}

	*o = ApexSeries(varApexSeries)

	return err
}

type NullableApexSeries struct {
	value *ApexSeries
	isSet bool
}

func (v NullableApexSeries) Get() *ApexSeries {
	return v.value
}

func (v *NullableApexSeries) Set(val *ApexSeries) {
	v.value = val
	v.isSet = true
}

func (v NullableApexSeries) IsSet() bool {
	return v.isSet
}

func (v *NullableApexSeries) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApexSeries(val *ApexSeries) *NullableApexSeries {
	return &NullableApexSeries{value: val, isSet: true}
}

func (v NullableApexSeries) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApexSeries) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
