/*
Synadia Control Plane / Synadia Cloud

API for Synadia Control Plane / Synadia Cloud

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

// checks if the ConnectorSink type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectorSink{}

// ConnectorSink struct for ConnectorSink
type ConnectorSink struct {
	Config Nullable[interface{}] `json:"config"`
	Type   string                `json:"type"`
}

func (o ConnectorSink) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !o.Config.IsNull() {
		toSerialize["config"] = o.Config.Val
	}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}
