/*
Synadia Control Plane / Synadia Cloud

API for Synadia Control Plane / Synadia Cloud

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

// checks if the ConnectorTransformerService type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectorTransformerService{}

// ConnectorTransformerService struct for ConnectorTransformerService
type ConnectorTransformerService struct {
	Endpoint   string              `json:"endpoint"`
	NatsConfig ConnectorNatsConfig `json:"nats_config"`
	Timeout    string              `json:"timeout"`
}

func (o ConnectorTransformerService) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["endpoint"] = o.Endpoint
	toSerialize["nats_config"] = o.NatsConfig
	toSerialize["timeout"] = o.Timeout
	return toSerialize, nil
}
