/*
Synadia Control Plane

API for Synadia Control Plane Server

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

import (
	"encoding/json"
	"fmt"
)

// checks if the TeamAppUserListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TeamAppUserListResponse{}

// TeamAppUserListResponse struct for TeamAppUserListResponse
type TeamAppUserListResponse struct {
	Items []TeamAppUserViewResponse `json:"items"`
}

type _TeamAppUserListResponse TeamAppUserListResponse

// NewTeamAppUserListResponse instantiates a new TeamAppUserListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTeamAppUserListResponse(items []TeamAppUserViewResponse) *TeamAppUserListResponse {
	this := TeamAppUserListResponse{}
	this.Items = items
	return &this
}

// NewTeamAppUserListResponseWithDefaults instantiates a new TeamAppUserListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTeamAppUserListResponseWithDefaults() *TeamAppUserListResponse {
	this := TeamAppUserListResponse{}
	return &this
}

// GetItems returns the Items field value
func (o *TeamAppUserListResponse) GetItems() []TeamAppUserViewResponse {
	if o == nil {
		var ret []TeamAppUserViewResponse
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *TeamAppUserListResponse) GetItemsOk() ([]TeamAppUserViewResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *TeamAppUserListResponse) SetItems(v []TeamAppUserViewResponse) {
	o.Items = v
}

func (o TeamAppUserListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TeamAppUserListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

func (o *TeamAppUserListResponse) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTeamAppUserListResponse := _TeamAppUserListResponse{}

	err = json.Unmarshal(bytes, &varTeamAppUserListResponse)

	if err != nil {
		return err
	}

	*o = TeamAppUserListResponse(varTeamAppUserListResponse)

	return err
}

type NullableTeamAppUserListResponse struct {
	value *TeamAppUserListResponse
	isSet bool
}

func (v NullableTeamAppUserListResponse) Get() *TeamAppUserListResponse {
	return v.value
}

func (v *NullableTeamAppUserListResponse) Set(val *TeamAppUserListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTeamAppUserListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTeamAppUserListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTeamAppUserListResponse(val *TeamAppUserListResponse) *NullableTeamAppUserListResponse {
	return &NullableTeamAppUserListResponse{value: val, isSet: true}
}

func (v NullableTeamAppUserListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTeamAppUserListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
