/*
Synadia Control Plane / Synadia Cloud

API for Synadia Control Plane / Synadia Cloud

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

// checks if the StreamExportSharedListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StreamExportSharedListResponse{}

// StreamExportSharedListResponse struct for StreamExportSharedListResponse
type StreamExportSharedListResponse struct {
	Items []StreamExportSharedViewResponse `json:"items"`
}

func (o StreamExportSharedListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	return toSerialize, nil
}
