/*
Synadia Control Plane

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

import (
	"encoding/json"
)

// checks if the AccountListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountListResponse{}

// AccountListResponse struct for AccountListResponse
type AccountListResponse struct {
	Items []AccountViewResponse `json:"items"`
}

// NewAccountListResponse instantiates a new AccountListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountListResponse(items []AccountViewResponse) *AccountListResponse {
	this := AccountListResponse{}
	this.Items = items
	return &this
}

// NewAccountListResponseWithDefaults instantiates a new AccountListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountListResponseWithDefaults() *AccountListResponse {
	this := AccountListResponse{}
	return &this
}

// GetItems returns the Items field value
func (o *AccountListResponse) GetItems() []AccountViewResponse {
	if o == nil {
		var ret []AccountViewResponse
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *AccountListResponse) GetItemsOk() ([]AccountViewResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *AccountListResponse) SetItems(v []AccountViewResponse) {
	o.Items = v
}

func (o AccountListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

type NullableAccountListResponse struct {
	value *AccountListResponse
	isSet bool
}

func (v NullableAccountListResponse) Get() *AccountListResponse {
	return v.value
}

func (v *NullableAccountListResponse) Set(val *AccountListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountListResponse(val *AccountListResponse) *NullableAccountListResponse {
	return &NullableAccountListResponse{value: val, isSet: true}
}

func (v NullableAccountListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
