/*
Synadia Control Plane / Synadia Cloud

API for Synadia Control Plane / Synadia Cloud

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

// checks if the BulkShareRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkShareRequest{}

// BulkShareRequest struct for BulkShareRequest
type BulkShareRequest struct {
	Id             string            `json:"id"`
	TargetAccounts []BulkShareTarget `json:"target_accounts"`
	Type           BulkShareType     `json:"type"`
}

func (o BulkShareRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["target_accounts"] = o.TargetAccounts
	toSerialize["type"] = o.Type
	return toSerialize, nil
}
