/*
Synadia Control Plane

API for Synadia Control Plane Server

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

import (
	"encoding/json"
	"fmt"
)

// checks if the InviteDecisionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InviteDecisionRequest{}

// InviteDecisionRequest struct for InviteDecisionRequest
type InviteDecisionRequest struct {
	Accept bool `json:"accept"`
}

type _InviteDecisionRequest InviteDecisionRequest

// NewInviteDecisionRequest instantiates a new InviteDecisionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInviteDecisionRequest(accept bool) *InviteDecisionRequest {
	this := InviteDecisionRequest{}
	this.Accept = accept
	return &this
}

// NewInviteDecisionRequestWithDefaults instantiates a new InviteDecisionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInviteDecisionRequestWithDefaults() *InviteDecisionRequest {
	this := InviteDecisionRequest{}
	return &this
}

// GetAccept returns the Accept field value
func (o *InviteDecisionRequest) GetAccept() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Accept
}

// GetAcceptOk returns a tuple with the Accept field value
// and a boolean to check if the value has been set.
func (o *InviteDecisionRequest) GetAcceptOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Accept, true
}

// SetAccept sets field value
func (o *InviteDecisionRequest) SetAccept(v bool) {
	o.Accept = v
}

func (o InviteDecisionRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InviteDecisionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accept"] = o.Accept
	return toSerialize, nil
}

func (o *InviteDecisionRequest) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"accept",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInviteDecisionRequest := _InviteDecisionRequest{}

	err = json.Unmarshal(bytes, &varInviteDecisionRequest)

	if err != nil {
		return err
	}

	*o = InviteDecisionRequest(varInviteDecisionRequest)

	return err
}

type NullableInviteDecisionRequest struct {
	value *InviteDecisionRequest
	isSet bool
}

func (v NullableInviteDecisionRequest) Get() *InviteDecisionRequest {
	return v.value
}

func (v *NullableInviteDecisionRequest) Set(val *InviteDecisionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInviteDecisionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInviteDecisionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInviteDecisionRequest(val *InviteDecisionRequest) *NullableInviteDecisionRequest {
	return &NullableInviteDecisionRequest{value: val, isSet: true}
}

func (v NullableInviteDecisionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInviteDecisionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
