/*
Synadia Control Plane

API for Synadia Control Plane Server

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

// checks if the Operator type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Operator{}

// Operator Operator specific claims
type Operator struct {
	GenericFields
	// AccountServerURL is a partial URL like \"https://host.domain.org:<port>/jwt/v1\" tools will use the prefix and build queries by appending /accounts/<account_id> or /operator to the path provided. Note this assumes that the account server can handle requests in a account-server compatible way. See https://github.com/nats-io/account-server.
	AccountServerUrl *string `json:"account_server_url,omitempty"`
	// Min Server version
	AssertServerVersion *string `json:"assert_server_version,omitempty"`
	// StringList is a wrapper for an array of strings
	OperatorServiceUrls *Nullable[[]string] `json:"operator_service_urls,omitempty"`
	// StringList is a wrapper for an array of strings
	SigningKeys *Nullable[[]string] `json:"signing_keys,omitempty"`
	// Signing of subordinate objects will require signing keys
	StrictSigningKeyUsage *bool `json:"strict_signing_key_usage,omitempty"`
	// Identity of the system account
	SystemAccount *string `json:"system_account,omitempty"`
}

func (o Operator) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.AccountServerUrl != nil {
		toSerialize["account_server_url"] = o.AccountServerUrl
	}
	if o.AssertServerVersion != nil {
		toSerialize["assert_server_version"] = o.AssertServerVersion
	}
	if o.OperatorServiceUrls != nil && !o.OperatorServiceUrls.IsNull() {
		toSerialize["operator_service_urls"] = o.OperatorServiceUrls.Val
	}
	if o.SigningKeys != nil && !o.SigningKeys.IsNull() {
		toSerialize["signing_keys"] = o.SigningKeys.Val
	}
	if o.StrictSigningKeyUsage != nil {
		toSerialize["strict_signing_key_usage"] = o.StrictSigningKeyUsage
	}
	if o.SystemAccount != nil {
		toSerialize["system_account"] = o.SystemAccount
	}
	if o.Tags != nil && !o.Tags.IsNull() {
		toSerialize["tags"] = o.Tags.Val
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Version != nil {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}
