/*
Synadia Control Plane / Synadia Cloud

API for Synadia Control Plane / Synadia Cloud

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

// checks if the WorkloadStartRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkloadStartRequest{}

// WorkloadStartRequest struct for WorkloadStartRequest
type WorkloadStartRequest struct {
	Auction           WorkloadAuctionRequest `json:"auction"`
	Description       string                 `json:"description"`
	Name              string                 `json:"name"`
	RunRequest        string                 `json:"run_request"`
	WorkloadLifecycle string                 `json:"workload_lifecycle"`
	WorkloadType      string                 `json:"workload_type"`
}

func (o WorkloadStartRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["auction"] = o.Auction
	toSerialize["description"] = o.Description
	toSerialize["name"] = o.Name
	toSerialize["run_request"] = o.RunRequest
	toSerialize["workload_lifecycle"] = o.WorkloadLifecycle
	toSerialize["workload_type"] = o.WorkloadType
	return toSerialize, nil
}
