/*
Synadia Control Plane / Synadia Cloud

API for Synadia Control Plane / Synadia Cloud

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

// checks if the AuthCalloutTargetAccountViewResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthCalloutTargetAccountViewResponse{}

// AuthCalloutTargetAccountViewResponse struct for AuthCalloutTargetAccountViewResponse
type AuthCalloutTargetAccountViewResponse struct {
	ControlAccountSkGroupId   string `json:"control_account_sk_group_id"`
	ControlAccountSkGroupName string `json:"control_account_sk_group_name"`
	Id                        string `json:"id"`
	TargetAccountId           string `json:"target_account_id"`
	TargetAccountName         string `json:"target_account_name"`
	TargetAccountSkGroupId    string `json:"target_account_sk_group_id"`
	TargetAccountSkGroupName  string `json:"target_account_sk_group_name"`
}

func (o AuthCalloutTargetAccountViewResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["control_account_sk_group_id"] = o.ControlAccountSkGroupId
	toSerialize["control_account_sk_group_name"] = o.ControlAccountSkGroupName
	toSerialize["id"] = o.Id
	toSerialize["target_account_id"] = o.TargetAccountId
	toSerialize["target_account_name"] = o.TargetAccountName
	toSerialize["target_account_sk_group_id"] = o.TargetAccountSkGroupId
	toSerialize["target_account_sk_group_name"] = o.TargetAccountSkGroupName
	return toSerialize, nil
}
