/*
Synadia Control Plane / Synadia Cloud

API for Synadia Control Plane / Synadia Cloud

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

// checks if the ConnectorComponentRange type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectorComponentRange{}

// ConnectorComponentRange struct for ConnectorComponentRange
type ConnectorComponentRange struct {
	Gt  *float32 `json:"gt,omitempty"`
	Gte *float32 `json:"gte,omitempty"`
	Lt  *float32 `json:"lt,omitempty"`
	Lte *float32 `json:"lte,omitempty"`
}

func (o ConnectorComponentRange) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Gt != nil {
		toSerialize["gt"] = o.Gt
	}
	if o.Gte != nil {
		toSerialize["gte"] = o.Gte
	}
	if o.Lt != nil {
		toSerialize["lt"] = o.Lt
	}
	if o.Lte != nil {
		toSerialize["lte"] = o.Lte
	}
	return toSerialize, nil
}
