/*
Synadia Control Plane

API for Synadia Control Plane Server

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

import (
	"encoding/json"
	"fmt"
)

// checks if the JetStreamAPIStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JetStreamAPIStats{}

// JetStreamAPIStats struct for JetStreamAPIStats
type JetStreamAPIStats struct {
	Errors int32 `json:"errors"`
	Total  int32 `json:"total"`
}

type _JetStreamAPIStats JetStreamAPIStats

// NewJetStreamAPIStats instantiates a new JetStreamAPIStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJetStreamAPIStats(errors int32, total int32) *JetStreamAPIStats {
	this := JetStreamAPIStats{}
	this.Errors = errors
	this.Total = total
	return &this
}

// NewJetStreamAPIStatsWithDefaults instantiates a new JetStreamAPIStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJetStreamAPIStatsWithDefaults() *JetStreamAPIStats {
	this := JetStreamAPIStats{}
	return &this
}

// GetErrors returns the Errors field value
func (o *JetStreamAPIStats) GetErrors() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value
// and a boolean to check if the value has been set.
func (o *JetStreamAPIStats) GetErrorsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Errors, true
}

// SetErrors sets field value
func (o *JetStreamAPIStats) SetErrors(v int32) {
	o.Errors = v
}

// GetTotal returns the Total field value
func (o *JetStreamAPIStats) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *JetStreamAPIStats) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *JetStreamAPIStats) SetTotal(v int32) {
	o.Total = v
}

func (o JetStreamAPIStats) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JetStreamAPIStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["errors"] = o.Errors
	toSerialize["total"] = o.Total
	return toSerialize, nil
}

func (o *JetStreamAPIStats) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"errors",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJetStreamAPIStats := _JetStreamAPIStats{}

	err = json.Unmarshal(bytes, &varJetStreamAPIStats)

	if err != nil {
		return err
	}

	*o = JetStreamAPIStats(varJetStreamAPIStats)

	return err
}

type NullableJetStreamAPIStats struct {
	value *JetStreamAPIStats
	isSet bool
}

func (v NullableJetStreamAPIStats) Get() *JetStreamAPIStats {
	return v.value
}

func (v *NullableJetStreamAPIStats) Set(val *JetStreamAPIStats) {
	v.value = val
	v.isSet = true
}

func (v NullableJetStreamAPIStats) IsSet() bool {
	return v.isSet
}

func (v *NullableJetStreamAPIStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJetStreamAPIStats(val *JetStreamAPIStats) *NullableJetStreamAPIStats {
	return &NullableJetStreamAPIStats{value: val, isSet: true}
}

func (v NullableJetStreamAPIStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJetStreamAPIStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
