/*
Synadia Control Plane

API for Synadia Control Plane Server

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

// checks if the AccountClaimsInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountClaimsInfo{}

// AccountClaimsInfo struct for AccountClaimsInfo
type AccountClaimsInfo struct {
	JsEnabled bool `json:"js_enabled"`
}

func (o AccountClaimsInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["js_enabled"] = o.JsEnabled
	return toSerialize, nil
}
