/*
Synadia Control Plane

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

import (
	"encoding/json"
)

// checks if the AlertRuleListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AlertRuleListResponse{}

// AlertRuleListResponse struct for AlertRuleListResponse
type AlertRuleListResponse struct {
	Items []AlertRuleViewResponse `json:"items"`
}

// NewAlertRuleListResponse instantiates a new AlertRuleListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlertRuleListResponse(items []AlertRuleViewResponse) *AlertRuleListResponse {
	this := AlertRuleListResponse{}
	this.Items = items
	return &this
}

// NewAlertRuleListResponseWithDefaults instantiates a new AlertRuleListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlertRuleListResponseWithDefaults() *AlertRuleListResponse {
	this := AlertRuleListResponse{}
	return &this
}

// GetItems returns the Items field value
func (o *AlertRuleListResponse) GetItems() []AlertRuleViewResponse {
	if o == nil {
		var ret []AlertRuleViewResponse
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *AlertRuleListResponse) GetItemsOk() ([]AlertRuleViewResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *AlertRuleListResponse) SetItems(v []AlertRuleViewResponse) {
	o.Items = v
}

func (o AlertRuleListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AlertRuleListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

type NullableAlertRuleListResponse struct {
	value *AlertRuleListResponse
	isSet bool
}

func (v NullableAlertRuleListResponse) Get() *AlertRuleListResponse {
	return v.value
}

func (v *NullableAlertRuleListResponse) Set(val *AlertRuleListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAlertRuleListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAlertRuleListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlertRuleListResponse(val *AlertRuleListResponse) *NullableAlertRuleListResponse {
	return &NullableAlertRuleListResponse{value: val, isSet: true}
}

func (v NullableAlertRuleListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlertRuleListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
