/*
Synadia Control Plane / Synadia Cloud

API for Synadia Control Plane / Synadia Cloud

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

// checks if the ChecksSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChecksSummary{}

// ChecksSummary struct for ChecksSummary
type ChecksSummary struct {
	Code        string   `json:"code"`
	Description string   `json:"description"`
	Examples    []string `json:"examples,omitempty"`
	Name        string   `json:"name"`
	Status      string   `json:"status"`
}

func (o ChecksSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["description"] = o.Description
	if len(o.Examples) != 0 {
		toSerialize["examples"] = o.Examples
	}
	toSerialize["name"] = o.Name
	toSerialize["status"] = o.Status
	return toSerialize, nil
}
