/*
Synadia Control Plane / Synadia Cloud

API for Synadia Control Plane / Synadia Cloud

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

// checks if the AccountOverviewResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountOverviewResponse{}

// AccountOverviewResponse struct for AccountOverviewResponse
type AccountOverviewResponse struct {
	AccountPublicKey string                         `json:"account_public_key"`
	Metrics          AccountOverviewResponseMetrics `json:"metrics"`
}

func (o AccountOverviewResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["account_public_key"] = o.AccountPublicKey
	toSerialize["metrics"] = o.Metrics
	return toSerialize, nil
}
