/*
Synadia Control Plane / Synadia Cloud

API for Synadia Control Plane / Synadia Cloud

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

// checks if the ConnectorConsumerPatch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectorConsumerPatch{}

// ConnectorConsumerPatch struct for ConnectorConsumerPatch
type ConnectorConsumerPatch struct {
	Core       *Nullable[ConnectorConsumerPatchCore]   `json:"core,omitempty"`
	Kv         *Nullable[ConnectorConsumerPatchKv]     `json:"kv,omitempty"`
	NatsConfig *ConnectorNatsConfigPatch               `json:"nats_config,omitempty"`
	Stream     *Nullable[ConnectorConsumerPatchStream] `json:"stream,omitempty"`
}

func (o ConnectorConsumerPatch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Core != nil && !o.Core.IsNull() {
		toSerialize["core"] = o.Core.Val
	}
	if o.Kv != nil && !o.Kv.IsNull() {
		toSerialize["kv"] = o.Kv.Val
	}
	if o.NatsConfig != nil {
		toSerialize["nats_config"] = o.NatsConfig
	}
	if o.Stream != nil && !o.Stream.IsNull() {
		toSerialize["stream"] = o.Stream.Val
	}
	return toSerialize, nil
}
