/*
Synadia Control Plane

API for Synadia Control Plane Server

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

// checks if the AppUserInfoListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppUserInfoListResponse{}

// AppUserInfoListResponse struct for AppUserInfoListResponse
type AppUserInfoListResponse struct {
	Items []AppUserInfo `json:"items"`
}

func (o AppUserInfoListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	return toSerialize, nil
}
