/*
Synadia Control Plane / Synadia Cloud

API for Synadia Control Plane / Synadia Cloud

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

// checks if the JSMirrorConfigRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JSMirrorConfigRequest{}

// JSMirrorConfigRequest struct for JSMirrorConfigRequest
type JSMirrorConfigRequest struct {
	JSCommonStreamConfig
	Mirror       StreamSource `json:"mirror"`
	MirrorDirect bool         `json:"mirror_direct"`
}

func (o JSMirrorConfigRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mirror"] = o.Mirror
	toSerialize["mirror_direct"] = o.MirrorDirect
	if o.AllowAtomic != nil {
		toSerialize["allow_atomic"] = o.AllowAtomic
	}
	if o.AllowBatched != nil {
		toSerialize["allow_batched"] = o.AllowBatched
	}
	toSerialize["allow_direct"] = o.AllowDirect
	if o.AllowMsgCounter != nil {
		toSerialize["allow_msg_counter"] = o.AllowMsgCounter
	}
	if o.AllowMsgSchedules != nil {
		toSerialize["allow_msg_schedules"] = o.AllowMsgSchedules
	}
	if o.AllowMsgTtl != nil {
		toSerialize["allow_msg_ttl"] = o.AllowMsgTtl
	}
	toSerialize["allow_rollup_hdrs"] = o.AllowRollupHdrs
	if o.Compression != nil {
		toSerialize["compression"] = o.Compression
	}
	if o.ConsumerLimits != nil {
		toSerialize["consumer_limits"] = o.ConsumerLimits
	}
	toSerialize["deny_delete"] = o.DenyDelete
	toSerialize["deny_purge"] = o.DenyPurge
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	toSerialize["discard"] = o.Discard
	if o.DiscardNewPerSubject != nil {
		toSerialize["discard_new_per_subject"] = o.DiscardNewPerSubject
	}
	if o.DuplicateWindow != nil {
		toSerialize["duplicate_window"] = o.DuplicateWindow
	}
	if o.FirstSeq != nil {
		toSerialize["first_seq"] = o.FirstSeq
	}
	toSerialize["max_age"] = o.MaxAge
	toSerialize["max_bytes"] = o.MaxBytes
	toSerialize["max_consumers"] = o.MaxConsumers
	if o.MaxMsgSize != nil {
		toSerialize["max_msg_size"] = o.MaxMsgSize
	}
	toSerialize["max_msgs"] = o.MaxMsgs
	toSerialize["max_msgs_per_subject"] = o.MaxMsgsPerSubject
	if len(o.Metadata) != 0 {
		toSerialize["metadata"] = o.Metadata
	}
	toSerialize["name"] = o.Name
	if o.NoAck != nil {
		toSerialize["no_ack"] = o.NoAck
	}
	toSerialize["num_replicas"] = o.NumReplicas
	if o.PersistMode != nil {
		toSerialize["persist_mode"] = o.PersistMode
	}
	if o.Placement != nil {
		toSerialize["placement"] = o.Placement
	}
	if o.Republish != nil {
		toSerialize["republish"] = o.Republish
	}
	toSerialize["retention"] = o.Retention
	toSerialize["sealed"] = o.Sealed
	if len(o.Sources) != 0 {
		toSerialize["sources"] = o.Sources
	}
	toSerialize["storage"] = o.Storage
	if o.SubjectDeleteMarkerTtl != nil {
		toSerialize["subject_delete_marker_ttl"] = o.SubjectDeleteMarkerTtl
	}
	if o.SubjectTransform != nil {
		toSerialize["subject_transform"] = o.SubjectTransform
	}
	if o.TemplateOwner != nil {
		toSerialize["template_owner"] = o.TemplateOwner
	}
	return toSerialize, nil
}
