/*
Synadia Control Plane / Synadia Cloud

API for Synadia Control Plane / Synadia Cloud

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

// checks if the ClusterInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterInfo{}

// ClusterInfo ClusterInfo shows information about the underlying set of servers that make up the stream or consumer.
type ClusterInfo struct {
	Leader         *string           `json:"leader,omitempty"`
	LeaderSince    *Nullable[string] `json:"leader_since,omitempty"`
	Name           *string           `json:"name,omitempty"`
	RaftGroup      *string           `json:"raft_group,omitempty"`
	Replicas       []PeerInfo        `json:"replicas,omitempty"`
	SystemAccount  *bool             `json:"system_account,omitempty"`
	TrafficAccount *string           `json:"traffic_account,omitempty"`
}

func (o ClusterInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Leader != nil {
		toSerialize["leader"] = o.Leader
	}
	if o.LeaderSince != nil && !o.LeaderSince.IsNull() {
		toSerialize["leader_since"] = o.LeaderSince.Val
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.RaftGroup != nil {
		toSerialize["raft_group"] = o.RaftGroup
	}
	if len(o.Replicas) != 0 {
		toSerialize["replicas"] = o.Replicas
	}
	if o.SystemAccount != nil {
		toSerialize["system_account"] = o.SystemAccount
	}
	if o.TrafficAccount != nil {
		toSerialize["traffic_account"] = o.TrafficAccount
	}
	return toSerialize, nil
}
