/*
Synadia Control Plane / Synadia Cloud

API for Synadia Control Plane / Synadia Cloud

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

// checks if the UpdateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateResponse{}

// UpdateResponse struct for UpdateResponse
type UpdateResponse struct {
	Revision int64 `json:"revision"`
	Version  int64 `json:"version"`
}

func (o UpdateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["revision"] = o.Revision
	toSerialize["version"] = o.Version
	return toSerialize, nil
}
