/*
Synadia Control Plane / Synadia Cloud

API for Synadia Control Plane / Synadia Cloud

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

// checks if the EntitlementsView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntitlementsView{}

// EntitlementsView struct for EntitlementsView
type EntitlementsView struct {
	Catalog        int64 `json:"catalog"`
	Connectors     int64 `json:"connectors"`
	Fleet          int64 `json:"fleet"`
	HttpGateway    int64 `json:"http_gateway"`
	Insights       int64 `json:"insights"`
	Protect        int64 `json:"protect"`
	SchemaRegistry int64 `json:"schema_registry"`
	Workloads      int64 `json:"workloads"`
}

func (o EntitlementsView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["catalog"] = o.Catalog
	toSerialize["connectors"] = o.Connectors
	toSerialize["fleet"] = o.Fleet
	toSerialize["http_gateway"] = o.HttpGateway
	toSerialize["insights"] = o.Insights
	toSerialize["protect"] = o.Protect
	toSerialize["schema_registry"] = o.SchemaRegistry
	toSerialize["workloads"] = o.Workloads
	return toSerialize, nil
}
