/*
Synadia Control Plane / Synadia Cloud

API for Synadia Control Plane / Synadia Cloud

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

// checks if the JSStreamInfoListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JSStreamInfoListResponse{}

// JSStreamInfoListResponse struct for JSStreamInfoListResponse
type JSStreamInfoListResponse struct {
	Items []JSStreamInfoResponse `json:"items"`
}

func (o JSStreamInfoListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	return toSerialize, nil
}
