/*
Synadia Control Plane / Synadia Cloud

API for Synadia Control Plane / Synadia Cloud

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

// checks if the SlackReceiverConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SlackReceiverConfig{}

// SlackReceiverConfig struct for SlackReceiverConfig
type SlackReceiverConfig struct {
	Config SlackConfig `json:"config"`
	Type   string      `json:"type"`
}

func (o SlackReceiverConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["config"] = o.Config
	toSerialize["type"] = o.Type
	return toSerialize, nil
}
