/*
Synadia Control Plane / Synadia Cloud

API for Synadia Control Plane / Synadia Cloud

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

// checks if the InsightsPlatformComponentConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InsightsPlatformComponentConfig{}

// InsightsPlatformComponentConfig struct for InsightsPlatformComponentConfig
type InsightsPlatformComponentConfig struct {
	Account string `json:"account"`
}

func (o InsightsPlatformComponentConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["account"] = o.Account
	return toSerialize, nil
}
