/*
Synadia Control Plane / Synadia Cloud

API for Synadia Control Plane / Synadia Cloud

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

// checks if the ConnectorConsumer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectorConsumer{}

// ConnectorConsumer struct for ConnectorConsumer
type ConnectorConsumer struct {
	Core       *ConnectorConsumerCore   `json:"core,omitempty"`
	Kv         *ConnectorConsumerKv     `json:"kv,omitempty"`
	NatsConfig ConnectorNatsConfig      `json:"nats_config"`
	Stream     *ConnectorConsumerStream `json:"stream,omitempty"`
}

func (o ConnectorConsumer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Core != nil {
		toSerialize["core"] = o.Core
	}
	if o.Kv != nil {
		toSerialize["kv"] = o.Kv
	}
	toSerialize["nats_config"] = o.NatsConfig
	if o.Stream != nil {
		toSerialize["stream"] = o.Stream
	}
	return toSerialize, nil
}
