/*
Synadia Control Plane / Synadia Cloud

API for Synadia Control Plane / Synadia Cloud

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

// checks if the ClusterOverview type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterOverview{}

// ClusterOverview struct for ClusterOverview
type ClusterOverview struct {
	Gateways         []GatewayConnection `json:"gateways,omitempty"`
	IncomingGateways int64               `json:"incoming_gateways"`
	JetstreamEnabled bool                `json:"jetstream_enabled"`
	Name             string              `json:"name"`
	NodeCount        int64               `json:"node_count"`
	Nodes            []string            `json:"nodes"`
	OutgoingGateways int64               `json:"outgoing_gateways"`
	TotalConnections int64               `json:"total_connections"`
	TotalCpuPercent  float32             `json:"total_cpu_percent"`
	TotalMemoryBytes int64               `json:"total_memory_bytes"`
	TotalRoutes      int64               `json:"total_routes"`
}

func (o ClusterOverview) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if len(o.Gateways) != 0 {
		toSerialize["gateways"] = o.Gateways
	}
	toSerialize["incoming_gateways"] = o.IncomingGateways
	toSerialize["jetstream_enabled"] = o.JetstreamEnabled
	toSerialize["name"] = o.Name
	toSerialize["node_count"] = o.NodeCount
	toSerialize["nodes"] = o.Nodes
	toSerialize["outgoing_gateways"] = o.OutgoingGateways
	toSerialize["total_connections"] = o.TotalConnections
	toSerialize["total_cpu_percent"] = o.TotalCpuPercent
	toSerialize["total_memory_bytes"] = o.TotalMemoryBytes
	toSerialize["total_routes"] = o.TotalRoutes
	return toSerialize, nil
}
