/*
Synadia Control Plane / Synadia Cloud

API for Synadia Control Plane / Synadia Cloud

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

import (
	"time"
)

// checks if the PriorityGroupState type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PriorityGroupState{}

// PriorityGroupState PriorityGroupState is the state of a consumer priority group.
type PriorityGroupState struct {
	Group          string     `json:"group"`
	PinnedClientId *string    `json:"pinned_client_id,omitempty"`
	PinnedTs       *time.Time `json:"pinned_ts,omitempty"`
}

func (o PriorityGroupState) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["group"] = o.Group
	if o.PinnedClientId != nil {
		toSerialize["pinned_client_id"] = o.PinnedClientId
	}
	if o.PinnedTs != nil {
		toSerialize["pinned_ts"] = o.PinnedTs
	}
	return toSerialize, nil
}
