/*
Synadia Control Plane / Synadia Cloud

API for Synadia Control Plane / Synadia Cloud

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

// checks if the AuthCalloutComponentConnectConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthCalloutComponentConnectConfig{}

// AuthCalloutComponentConnectConfig struct for AuthCalloutComponentConnectConfig
type AuthCalloutComponentConnectConfig struct {
	ConfigSchema []PlatformComponentsConfigSchema `json:"config_schema"`
	Type         string                           `json:"type"`
}

func (o AuthCalloutComponentConnectConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["config_schema"] = o.ConfigSchema
	toSerialize["type"] = o.Type
	return toSerialize, nil
}
