/*
Synadia Control Plane

API for Synadia Control Plane Server

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syncp

import (
	"encoding/json"
)

// checks if the JetStreamStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JetStreamStats{}

// JetStreamStats Statistics about JetStream for this server.
type JetStreamStats struct {
	Accounts        int32             `json:"accounts"`
	Api             JetStreamAPIStats `json:"api"`
	HaAssets        int32             `json:"ha_assets"`
	Memory          int32             `json:"memory"`
	ReservedMemory  int32             `json:"reserved_memory"`
	ReservedStorage int32             `json:"reserved_storage"`
	Storage         int32             `json:"storage"`
}

// NewJetStreamStats instantiates a new JetStreamStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJetStreamStats(accounts int32, api JetStreamAPIStats, haAssets int32, memory int32, reservedMemory int32, reservedStorage int32, storage int32) *JetStreamStats {
	this := JetStreamStats{}
	this.Accounts = accounts
	this.Api = api
	this.HaAssets = haAssets
	this.Memory = memory
	this.ReservedMemory = reservedMemory
	this.ReservedStorage = reservedStorage
	this.Storage = storage
	return &this
}

// NewJetStreamStatsWithDefaults instantiates a new JetStreamStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJetStreamStatsWithDefaults() *JetStreamStats {
	this := JetStreamStats{}
	return &this
}

// GetAccounts returns the Accounts field value
func (o *JetStreamStats) GetAccounts() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Accounts
}

// GetAccountsOk returns a tuple with the Accounts field value
// and a boolean to check if the value has been set.
func (o *JetStreamStats) GetAccountsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Accounts, true
}

// SetAccounts sets field value
func (o *JetStreamStats) SetAccounts(v int32) {
	o.Accounts = v
}

// GetApi returns the Api field value
func (o *JetStreamStats) GetApi() JetStreamAPIStats {
	if o == nil {
		var ret JetStreamAPIStats
		return ret
	}

	return o.Api
}

// GetApiOk returns a tuple with the Api field value
// and a boolean to check if the value has been set.
func (o *JetStreamStats) GetApiOk() (*JetStreamAPIStats, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Api, true
}

// SetApi sets field value
func (o *JetStreamStats) SetApi(v JetStreamAPIStats) {
	o.Api = v
}

// GetHaAssets returns the HaAssets field value
func (o *JetStreamStats) GetHaAssets() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.HaAssets
}

// GetHaAssetsOk returns a tuple with the HaAssets field value
// and a boolean to check if the value has been set.
func (o *JetStreamStats) GetHaAssetsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HaAssets, true
}

// SetHaAssets sets field value
func (o *JetStreamStats) SetHaAssets(v int32) {
	o.HaAssets = v
}

// GetMemory returns the Memory field value
func (o *JetStreamStats) GetMemory() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Memory
}

// GetMemoryOk returns a tuple with the Memory field value
// and a boolean to check if the value has been set.
func (o *JetStreamStats) GetMemoryOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Memory, true
}

// SetMemory sets field value
func (o *JetStreamStats) SetMemory(v int32) {
	o.Memory = v
}

// GetReservedMemory returns the ReservedMemory field value
func (o *JetStreamStats) GetReservedMemory() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ReservedMemory
}

// GetReservedMemoryOk returns a tuple with the ReservedMemory field value
// and a boolean to check if the value has been set.
func (o *JetStreamStats) GetReservedMemoryOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReservedMemory, true
}

// SetReservedMemory sets field value
func (o *JetStreamStats) SetReservedMemory(v int32) {
	o.ReservedMemory = v
}

// GetReservedStorage returns the ReservedStorage field value
func (o *JetStreamStats) GetReservedStorage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ReservedStorage
}

// GetReservedStorageOk returns a tuple with the ReservedStorage field value
// and a boolean to check if the value has been set.
func (o *JetStreamStats) GetReservedStorageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReservedStorage, true
}

// SetReservedStorage sets field value
func (o *JetStreamStats) SetReservedStorage(v int32) {
	o.ReservedStorage = v
}

// GetStorage returns the Storage field value
func (o *JetStreamStats) GetStorage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Storage
}

// GetStorageOk returns a tuple with the Storage field value
// and a boolean to check if the value has been set.
func (o *JetStreamStats) GetStorageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Storage, true
}

// SetStorage sets field value
func (o *JetStreamStats) SetStorage(v int32) {
	o.Storage = v
}

func (o JetStreamStats) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JetStreamStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accounts"] = o.Accounts
	toSerialize["api"] = o.Api
	toSerialize["ha_assets"] = o.HaAssets
	toSerialize["memory"] = o.Memory
	toSerialize["reserved_memory"] = o.ReservedMemory
	toSerialize["reserved_storage"] = o.ReservedStorage
	toSerialize["storage"] = o.Storage
	return toSerialize, nil
}

type NullableJetStreamStats struct {
	value *JetStreamStats
	isSet bool
}

func (v NullableJetStreamStats) Get() *JetStreamStats {
	return v.value
}

func (v *NullableJetStreamStats) Set(val *JetStreamStats) {
	v.value = val
	v.isSet = true
}

func (v NullableJetStreamStats) IsSet() bool {
	return v.isSet
}

func (v *NullableJetStreamStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJetStreamStats(val *JetStreamStats) *NullableJetStreamStats {
	return &NullableJetStreamStats{value: val, isSet: true}
}

func (v NullableJetStreamStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJetStreamStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
