/*
Synadia Control Plane / Synadia Cloud

Testing OidcProviderAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package syncp

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	openapiclient "github.com/synadia-io/control-plane-sdk-go/syncp"
)

func Test_syncp_OidcProviderAPIService(t *testing.T) {
	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test OidcProviderAPIService CreateOidcProvider", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.OidcProviderAPI.CreateOidcProvider(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test OidcProviderAPIService DeleteOidcProvider", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var oidcProviderId string

		httpRes, err := apiClient.OidcProviderAPI.DeleteOidcProvider(context.Background(), oidcProviderId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test OidcProviderAPIService GetOidcProvider", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var oidcProviderId string

		resp, httpRes, err := apiClient.OidcProviderAPI.GetOidcProvider(context.Background(), oidcProviderId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test OidcProviderAPIService ListOidcDefaultProvider", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.OidcProviderAPI.ListOidcDefaultProvider(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test OidcProviderAPIService ListOidcProviders", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.OidcProviderAPI.ListOidcProviders(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test OidcProviderAPIService UpdateOidcProvider", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var oidcProviderId string

		resp, httpRes, err := apiClient.OidcProviderAPI.UpdateOidcProvider(context.Background(), oidcProviderId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})
}
