/*
Synadia Control Plane

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the TeamListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TeamListResponse{}

// TeamListResponse struct for TeamListResponse
type TeamListResponse struct {
	Items []TeamViewResponse `json:"items"`
}

// NewTeamListResponse instantiates a new TeamListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTeamListResponse(items []TeamViewResponse) *TeamListResponse {
	this := TeamListResponse{}
	this.Items = items
	return &this
}

// NewTeamListResponseWithDefaults instantiates a new TeamListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTeamListResponseWithDefaults() *TeamListResponse {
	this := TeamListResponse{}
	return &this
}

// GetItems returns the Items field value
func (o *TeamListResponse) GetItems() []TeamViewResponse {
	if o == nil {
		var ret []TeamViewResponse
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *TeamListResponse) GetItemsOk() ([]TeamViewResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *TeamListResponse) SetItems(v []TeamViewResponse) {
	o.Items = v
}

func (o TeamListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TeamListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

type NullableTeamListResponse struct {
	value *TeamListResponse
	isSet bool
}

func (v NullableTeamListResponse) Get() *TeamListResponse {
	return v.value
}

func (v *NullableTeamListResponse) Set(val *TeamListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTeamListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTeamListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTeamListResponse(val *TeamListResponse) *NullableTeamListResponse {
	return &NullableTeamListResponse{value: val, isSet: true}
}

func (v NullableTeamListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTeamListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
